language: java

jdk:
  - oraclejdk8

after_success:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package -Dmaven.test.failure.ignore=true  sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=15838028035-github  -Dsonar.login=$SONAR_CLOUD_TOKEN deploy  -X
notifications:
  email:
    - 15838028035@163.com

sudo: required
